Fix plantuml output
samwilson/diagrams-extension pull request #49
Opened 2022-01-10 17:34 UTC by ewie

Fixes #30:
* `-syntax' option only checks `stdin` which is not used by this extension.
* Determine output file from input file instead of creating a temporary file for the output.

2022-01-11 00:58 UTC, samwilson requested changes
Thanks for this! Looks great.

2022-01-11 00:58 UTC, samwilson commented on includes/Diagrams.php
> +				$input = "@startuml\n$input\n@enduml";
This wrapping in start/end is already being done below, so this results in double-wrapping.

2022-01-11 00:58 UTC, samwilson commented on includes/Diagrams.php
>  			if ( $commandName === 'plantuml' ) {
This conditional can probably now be removed.

2022-01-11 00:58 UTC, samwilson commented on includes/Diagrams.php
> +				$tmpOutFiles[$outputType] = new FSFile( $outputPath );
Should use `TempFSFile`.

2022-01-11 11:22 UTC, ewie commented on includes/Diagrams.php
> +				$input = "@startuml\n$input\n@enduml";
Copy-paste error. Interestingly, PlantUML ignores the double-wrapping.

2022-01-11 11:23 UTC, ewie commented on includes/Diagrams.php
>  			if ( $commandName === 'plantuml' ) {
Done

2022-01-11 11:23 UTC, ewie commented on includes/Diagrams.php
> +				$tmpOutFiles[$outputType] = new FSFile( $outputPath );
Done

2022-01-12 01:41 UTC, samwilson approved these changes

2022-01-12 01:42 UTC, merged