Fixing issue where isPreview would be false, even when previewing the edit
samwilson/diagrams-extension pull request #68
Opened 2022-12-10 18:57 UTC by YOUR1

Tested and its working as it should now. We might change the version to 1.0.0 - since I can't no longer find any bugs, and also update the https://www.mediawiki.org/wiki/Extension:Diagrams page to 'stable'.

2022-12-10 19:01 UTC, YOUR1 commented
Pinging @samwilson so we can tag a new version with this fix (and I could actually use it in production :) )

2022-12-13 00:21 UTC, samwilson requested changes
Thanks for working on this. Could you please explain a bit more about the bug you're experiencing? i.e. what is happening, and how do you replicate it. Your other PR (#62) seems to have been about the same issue.

The commit message should explain why there's a difference between calling this on the Parser object passed to the ParserFirstCallInit hook and calling it on the main Parser service.

2022-12-13 00:21 UTC, samwilson commented on includes/Diagrams.php
> +		$status = MediaWikiServices::getInstance()->getParser()->getOptions()->getIsPreview()
`Parser::getOptions()` can return null here, so that needs to be accounted for.

2022-12-13 09:18 UTC, YOUR1 commented
> Thanks for working on this. Could you please explain a bit more about the bug you're experiencing? i.e. what is happening, and how do you replicate it. Your other PR (#62) seems to have been about the same issue.
> 
> The commit message should explain why there's a difference between calling this on the Parser object passed to the ParserFirstCallInit hook and calling it on the main Parser service.

No problem. The issue is fairly easy to reproduce: 
- create a graphviz diagram and save page
- edit page - and press preview changes
A error will occur now, saying that the file already exists, thus isn't showed. 

The underlying problem for this issue is that the isPreview-bool is always false. This is because the parserCallFirstInit hook is called BEFORE the isPreview boolean is set correctly. To workaround this issue, I used MediaWikiServers::getInstance()->getParser(), since it has the 'correct' object.

2022-12-17 11:09 UTC, samwilson requested changes
The issue you describe is #32 isn't it? It doesn't seem that it's actually related to previewing at all.

I've been looking into it a bit more, and I'm now thinking that we should probably get rid of any special handling for previewing. Basically, #50 is still unresolved, and any solution for that will work for orphaned preview files as well as others — and it looks like it'll be simpler to just have one way of rendering files.

I'll make a PR with what I'm thinking.

2022-12-17 11:09 UTC, samwilson commented on includes/Diagrams.php
> +		$parserOptions = MediaWikiServices::getInstance()->getParser()->getOptions();
I still think the Parser object from the hook handler should be passed in. It looks like the correct way to do this would be to call `getIsPreview()` within the [hook callback](https://github.com/samwilson/diagrams-extension/blob/7791b1403e6a59977f423b49efe5810e7c4b443b/includes/Hooks.php#L35), because at that point isPreview will have been set.

However, see my other comment; I think it's better to get rid of previewing.

2022-12-20 07:26 UTC, YOUR1 commented on includes/Diagrams.php
> +		$parserOptions = MediaWikiServices::getInstance()->getParser()->getOptions();
It looks like that yes, but the options is never fully initialised from within that hook. I do think its very unfortunate that you keep this branch open, since it actually does fix the nasty bug thats in master now. I personally would suggest merging this branch and then look for another approach.

2022-12-20 07:42 UTC, samwilson commented on includes/Diagrams.php
> +		$parserOptions = MediaWikiServices::getInstance()->getParser()->getOptions();
I'm not sure I understand what you mean by "ParserOptions is never fully initialised from within that hook." The bug is that we're reading isPreview before it's been set, and the fix is as I've shown in #73, to move the reading of it into the `setHook()` callback.

However, I still think it's not actually necessary to have special handling for preview files, and am currently focused on #74 which will make it possible to remove the preview flag altogether.

Which I think means you're right, and this PR can be closed.

2022-12-20 07:50 UTC, closed without merging